name: Publish 1.5

on:
  push:
    branches:
      - "dev/1.6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v1
      - run: cd test-mod && ./gradlew
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}
